version: 0.0
os: linux
files:
   - source: /
    destination: /deploy
hooks:
  ApplicationStart:
    - location: pipeline/configurationParser.py
      timeout: 300
      runas: root
    - location: pipeline/geocodeUdf.py
      timeout: 300
      runas: root
    - location: pipeline/ingest.py
      timeout: 300
      runas: root
    - location: pipeline/persist.py
      timeout: 300
      runas: root
    - location: pipeline/transform.py
      timeout: 300
      runas: root
    - location:  main.py
      timeout: 300
      runas: root
