version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.8
        commands:
          # Install dependencies needed for running tests
          #- pip install -r requirements/common.txt
          - echo "[Install phase]"
          - pip3 install configparser
          - pip3 install pipeline
          - pip3 install logging
          - pip3 install pandas
          - pip3 install psycopg2
          - pip3 install pyspark.sql.functions
          - pip3 install pyspark.sql.types
  pre_build:
    commands:
      - python main.py test
build:
    commands:
      - python -m configparser
      - python -m pipeline
      - python -m logging
      - python -m pandas
      - python -m psycopg2
      - python -m pyspark.sql.functions
      - python -m pyspark.sql.types

      post_build:
        commands:
          - echo Build completed on `date`
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml

artifacts:
  type: zip
  files:
    - 'resources/**/*'
    - 'configurationParser.py'
    - 'geocodeUdf.py'
    - 'ingest.py'
    - 'persist.py'
    - 'transform.py'
    - 'main.py'


      cache:
        paths:
          - '/root/.cache/pip'
