version: 0.2

phases:
 pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
 build:
    commands:
      - echo Build started on `date`
      - pip3 install configparser
      - pip3 install pipeline
      - pip3 install pandas
      - pip3 install psycopg2
      - pip3 install pyspark     
 post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
   
