version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.8
        commands:
          # Install dependencies needed for running tests
          #- pip install -r requirements/common.txt
          - echo "[Install phase]"
          - pip3 install configparser
          - pip3 install pipeline
          - pip3 install logging
          - pip3 install pandas
          - pip3 install psycopg2
          - pip3 install pyspark.sql.functions
          - pip3 install pyspark.sql.types
  pre_build:
    commands:
      post_build:
        commands:
artifacts:
  type: zip
  files:
    - 'resources/**/*'
    - 'configurationParser.py'
    - 'geocodeUdf.py'
    - 'ingest.py'
    - 'persist.py'
    - 'transform.py'
    - 'main.py'
      cache:
        paths:
          - '/root/.cache/pip'
